services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.03-trtllm-python-py3
    command: ["tritonserver", "--model-repository=/models", "--model-control-mode=explicit", "--log-verbose=3", "--backend-config=tensorrt,version-compatible=true"]
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - "./models:/models"
    shm_size: "2gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
